### ISSUE TITLE
Experimentar vs Experimentacion

### ISSUE THREAD

**Issue by jjruescas** [rodrigojmartin/principios_del_caos#3]
@rodrigojmartin .
Que opinarías de modificar esta parte en la definición, basado en la traducción del inglés?
"La Ingeniería del Caos es la disciplina de **experimentar** en un sistema " por 
"La Ingeniería del Caos es la disciplina de **experimentación** en un sistema".

En ingles "Experimenting" es un poco dificil de traducir porque es un gerundio, pero al ponerlo en "Experimentación" tal vez suena mejor en Español.

**Comment by rodrigojmartin** [comment]
Hola @jjruescas , muchas gracias por la recomendación, ahora lo corrijo. 
Saludos!
